name: Master Branch

on:
  push:
    branches:
      - 'main'

jobs:
  cloud:
    name: login cloud
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v2
      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST_CLOUD }}
            USERNAME: ROOT
            PORT: 22
            password: ${{ secrets.KEY_CLOUD }}
              script:| docker pull 030065/course
   
         
            
